### ISSUE TITLE
Un problème de Setup

### ISSUE THREAD

**Issue by PinganYANG** [Ordisoftware/Hieroglyphics-Decoder#127]
Bonjour Monsieur,
Je m'intéresse à ce projet et je clone tous les documents localement. Et je télécharge inno setup pour lancer .iss files. Mais quand je lance ```Hieroglyphics-Decoder/Setup/OrdisoftwareHieroglyphicsDecoderSetup.iss```, il y a un problème dans le ```Hieroglyphics-Decoder/Setup/Scripts/Files.iss``` lignes 4 ```Source: ..\Bin\Release\*; DestDir: {app}\Bin; Flags: ignoreversion recursesubdirs; Excludes: *vshost.exe```, avec l'erreur ```No files found matching```.

Je pense c'est à cause du manque d'un folder /Bin

Bien cordialement

---------------------------------------
Hello Sir,
I am interested in this project and I am cloning all the documents locally. And I am downloading Inno Setup to launch .iss files. But when I run ```Hieroglyphics-Decoder/Setup/OrdisoftwareHieroglyphicsDecoderSetup.iss```, there is a problem in the ```Hieroglyphics-Decoder/Setup/Scripts/Files.iss``` line 4 ```Source: ..\Bin\Release\*; DestDir: {app}\Bin; Flags: ignoreversion recursesubdirs; Excludes: *vshost.exe```, with the error ```No files found matching```.

I think it is due to the lack of a /Bin folder.

Best regards

**Comment by Ordisoftware** [comment]
Bonjour Monsieur,

Il est en effet nécessaire de compiler le projet en mode release pour obtenir les fichiers binaires à inclure dans le setup.

Gardez cependant à l'esprit que le projet n'a pas encore commencé : j'ai juste créé le repo GitHub avec la structure de base du système de fichiers et une solution presque vide car ne comportant que le Core Library commun aux projets hébraïques. Le logiciel n'est donc pour le moment qu'une WinForm vide.

Les développements ne devraient pas commencer avant longtemps car je pense d'abord réaliser le Furthark Decoder plus simple et de même difficulté que Hebrew Letters dont il sera un clone pour les runes. Pour les hiéroglyphes il y aura plus de travail en raison du nombre de signes et de l'étude à effectuer en ce qui me concerne puisque je n'y connais presque rien et je n'ai à ce jour décodé à la main que quelques dizaines de shenou, ce qui m'a donné l'idée de transposer [l'analyseur de lettres hébraïques](https://github.com/Ordisoftware/Hebrew-Letters).

L'interface visuelle, l'ergonomie et les fonctionnalités du Futhark et du Hieroglyphic Decoders seront identiques à très peu de choses près à Letters sauf que ce dernier comportera un composeur de shenou différent du panneau de saisie des lettres hébraïques ou runiques au sujet duquel il faudra réfléchir... Mais il me faut en premier lieu terminer le notebook de Letters.

Cordialement,
Olivier

![image](https://user-images.githubusercontent.com/22332878/233828373-013d2724-dd1a-4646-8a05-381ab1b961aa.png)
